name: Build Release Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  Build-Release-Android-APK:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'androide')"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "setup-node@v3"
        uses: actions/setup-node@v3
        with:
          node-version: 18                                             
      - name: "Install Node Dependencies"
        run: |
          npm i
      - name: "Build and Release"
        run: |
          cd android     
          chmod a+x gradlew
          ./gradlew -v
          ./gradlew clean
          ./gradlew build
          ./gradlew assembleRelease
          ./gradlew app:bundleRelease
          pwd
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Build artifact
          path: ./android/app/build/outputs/apk/release/app-release.apk
      - name: "upload apk to App Center"
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: "jeyapriya/apktest"
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: testers
          file: ./android/app/build/outputs/apk/release/app-release.apk 
          notifyTesters: "true"
          debug: "false"
