name: Build Release Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  Build-Release-Android-APK:
    runs-on: "ubuntu-latest"
    if: "contains(github.event.head_commit.message, 'android')"
    
    steps:
    
      - name: "Checkout Code"
        uses: actions/checkout@v3
      - name: "setup-node@v3"
        uses: actions/setup-node@v3
        with:
          node-version: 18                                             
      - name: "Install Node Dependencies"
        run: |
          npm i
      - name: "Build and Release"
        run: |
          cd android     
          chmod a+x gradlew
          ./gradlew -v
          ./gradlew clean
          ./gradlew build
          ./gradlew assembleRelease
          ./gradlew app:bundleRelease
          pwd
        env:
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      - name: Upload Release Build to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          paths: |
            app/build/outputs/apk/release/
            app/build/outputs/bundle/release/
          
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          prerelease: true
          files: |
            app/build/outputs/apk/release/app-release.apk
            app/build/outputs/bundle/release/app-release.aab
